---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: netplan-ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroupns_mode: host
provisioner:
  name: ansible
  lint: ansible-lint --force-color
lint: |
  set -e
  yamllint .
  ansible-lint
verifier:
  name: ansible
